# Generated by Django 3.0.9 on 2020-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='more',
            field=models.URLField(blank=True, default='https://www.google.com', max_length=1000, null=True),
        ),
    ]
