# Generated by Django 3.0.9 on 2020-10-03 19:33

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200928_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='/home/alireza/Desktop/Prozesh/prozesh-apis/media//uploads/images/default.jpg', upload_to=account.models.user_dir_path),
        ),
    ]
