# Generated by Django 3.0.9 on 2020-10-03 19:33

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFrameWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='language.CommentFrameWork')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='language.CommentLanguage')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='framework',
            name='lang',
            field=models.CharField(choices=[('HTML5', 'HTML'), ('Bootstrap4', 'Bootstrap4'), ('Css3', 'Css3'), ('Js', 'js'), ('Kotlin', 'Kotlin'), ('Java', 'java'), ('C++', 'C++'), ('Perl', 'Perl'), ('C-Sharp', 'C-Sharp'), ('Python', 'Python'), ('GraphQL', 'GraphQL'), ('REST', 'REST'), ('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLServer', 'SQLServer'), ('linux', 'linux'), ('git', 'git'), ('docker', 'docker')], default='HTML', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('HTML5', 'HTML'), ('Bootstrap4', 'Bootstrap4'), ('Css3', 'Css3'), ('Js', 'js'), ('Kotlin', 'Kotlin'), ('Java', 'java'), ('C++', 'C++'), ('Perl', 'Perl'), ('C-Sharp', 'C-Sharp'), ('Python', 'Python'), ('GraphQL', 'GraphQL'), ('REST', 'REST'), ('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLServer', 'SQLServer'), ('linux', 'linux'), ('git', 'git'), ('docker', 'docker')], default='HTML', max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='commentlanguage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='language.Language'),
        ),
        migrations.AddField(
            model_name='commentframework',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='language.FrameWork'),
        ),
    ]
